[docs] Add initial SCP documentation
stakecube/StakeCubeProtocol pull request #12
Opened 2021-07-15 06:33 UTC by sc-9310

This is the beginning for the SCP documentation, which includes the following:

- Readme
- Release notes for v1.1.3 and v.1.1.4
- Protocol descriptions for SCP-1 and SCP-2
- Installation guides in English and German
- Dependency list
- Contribution guidelines
- Extracted API endpoint lists

2021-07-15 17:13 UTC, JSKitty requested changes
Now that a 'proper' API routes system PR has been submitted, we can update the API documentation in this PR too.

2021-07-15 19:09 UTC, sc-9310 commented
Definitely. Can you somehow _highlight_ the endpoints are supported full node only; comments or similar? Will expand API docs and want to reflect fallback yes/no too.

2021-07-15 22:04 UTC, JSKitty requested changes

2021-07-15 22:04 UTC, JSKitty commented on docs/protocols/scp-1.md
> +This fee is irrecoverable 'burned'.
irrecoverabl**y**(?), otherwise it reads as `irrecoverable burned`, or we could use: `... irrecoverable. e.g; burned.`

2021-07-15 22:04 UTC, JSKitty commented on docs/protocols/scp-2.md
> +This fee is irrecoverable 'burned'.
Same comment as applied to the SCP-1 document.

2021-07-16 05:28 UTC, sc-9310 commented on docs/guides/en/installation.md
> +rpcpassword=passwort
It's a german password :P

2021-07-19 11:11 UTC, sc-9310 commented
Requesting new review now.

Note, examples pointing to stakecubecoin.net/web3/scp will not work until SCP is updated to newest changes as stated here: 3428032

2021-07-19 11:23 UTC, JSKitty approved these changes

2021-07-19 11:43 UTC, merged